# Site settings
title: farischebib.is
name: faris chebib
description: "a happy-go-lucky cognitive science hacker"
url: "https://farischebib.is"
baseurl: ""

# More profile stuff
github_username:  octaflop
twitter_username: siraf
google_plus_username: FarisChebib
linked_in_username: farisc
instagram_username:  octaflop
flickr_username: fyrefoenix
steam_username: fyrefoenix
stack_of_username: 10636
hacking_blog_url: "/hacking"
email: faris@theluckybead.com
public_key_url: "https://keybase.io/faris"


avatar: yes
avatar_img_path: "imgs/profile.jpg"

front_img: yes
front_img_path: "/imgs/background.jpg"

logo: "/imgs/profile.jpg"
cover: "/imgs/background.jpg"

# Social
name: "Faris Chebib"
author: "Faris Chebib"
social:
  - icon: github
    url: https://github.com/octaflop

paginate: 5
paginate_path: "/all/page:num/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jemoji
  - jekyll-paginate
